/*
 * SPDX-FileCopyrightText: 2015-2017 Tyler Burton <software@tylerburton.ca>
 * SPDX-FileCopyrightText: 2015-2025 The ObjGTK authors, see AUTHORS file
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

#import <ObjFW/ObjFW.h>


// Generated classes
#import "OGEClient.h"
#import "OGEExtension.h"
#import "OGENetworkMonitor.h"
#import "OGEOAuth2ServiceBase.h"
#import "OGEOAuth2ServiceGoogle.h"
#import "OGEOAuth2ServiceOutlook.h"
#import "OGEOAuth2ServiceYahoo.h"
#import "OGEOAuth2Services.h"
#import "OGESource.h"
#import "OGESourceAddressBook.h"
#import "OGESourceAlarms.h"
#import "OGESourceAuthentication.h"
#import "OGESourceAutocomplete.h"
#import "OGESourceAutoconfig.h"
#import "OGESourceBackend.h"
#import "OGESourceCalendar.h"
#import "OGESourceCamel.h"
#import "OGESourceCollection.h"
#import "OGESourceContacts.h"
#import "OGESourceCredentialsProvider.h"
#import "OGESourceCredentialsProviderImpl.h"
#import "OGESourceCredentialsProviderImplOAuth2.h"
#import "OGESourceCredentialsProviderImplPassword.h"
#import "OGESourceExtension.h"
#import "OGESourceGoa.h"
#import "OGESourceLDAP.h"
#import "OGESourceLocal.h"
#import "OGESourceMDN.h"
#import "OGESourceMailAccount.h"
#import "OGESourceMailComposition.h"
#import "OGESourceMailIdentity.h"
#import "OGESourceMailSignature.h"
#import "OGESourceMailSubmission.h"
#import "OGESourceMailTransport.h"
#import "OGESourceMemoList.h"
#import "OGESourceOffline.h"
#import "OGESourceOpenPGP.h"
#import "OGESourceProxy.h"
#import "OGESourceRefresh.h"
#import "OGESourceRegistry.h"
#import "OGESourceRegistryWatcher.h"
#import "OGESourceResource.h"
#import "OGESourceRevisionGuards.h"
#import "OGESourceSMIME.h"
#import "OGESourceSecurity.h"
#import "OGESourceSelectable.h"
#import "OGESourceTaskList.h"
#import "OGESourceUoa.h"
#import "OGESourceWeather.h"
#import "OGESourceWebDAVNotes.h"
#import "OGESourceWebdav.h"
#import "OGEXmlDocument.h"
